# -*- coding: utf-8 -*-
"""Quantium task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zDV2MrwbWXWhMIJ6HVeMmpLyyzU0LQ_Y
"""

import pandas as pd
import numpy as np
import seaborn as sns

dataset = pd.read_excel('/QVI_transaction_data.xlsx')

dataset.head()

"""# **SUMMARIZARTION**

"""

dataset.describe()

dataset.isnull().sum()

"""# **CHECKING FOR OUTLIERS**"""

sns.boxplot(dataset.TOT_SALES)

sns.displot(dataset.TOT_SALES, kde=True)

numericdata = dataset.select_dtypes(['float', 'int'])

numericdata.head()

"""# **REMOVING OUTLIERS**"""

x = numericdata[numericdata['TOT_SALES']< 8.000]

sns.displot(x.TOT_SALES, kde = True)

sns.boxplot(x.TOT_SALES)

"""# **DATA FORMETS**"""

dataset.dtypes

